apps/portfolio/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views  # This line is new!
from .views import Pdf
from .views import wishmaker

urlpatterns = [
    url(r"^$", views.main),
    url(r"^home/$", views.home, name="home"),
    url(r"^python/$", views.python, name="python"),
    url(r"^csharp/$", views.csharp, name="csharp"),
    url(r"^about/$", views.about, name="about"),
    url(r"^about/Pdf/$", views.Pdf, name="Pdf"),
    url(r"^wishmaker/$", views.wishmaker, name="wishmaker"),
    url(r"^wishmakersite/$", views.wishmakersite, name="wishmakersite"),
    url(r"^quotedash/$", views.quotedash, name="quotedash"),
    url(r"^quotedashsite/$", views.quotedashsite, name="quotedashsite"),
    url(r"^contact/$", views.contact, name="contact"),
    url(r"^clakkle/$", views.clakkle, name="clakkle"),
    url(r"^weddingplanner/$", views.weddingplanner, name="weddingplanner"),
    url(r"^weddingplannersite/$", views.weddingplannersite, name="weddingplannersite"),
    url(r"^healthwall/$", views.healthwall, name="healthwall"),
    url(r"^healthwallsite/$", views.healthwallsite, name="healthwallsite"),
    url(r"^linkedIn/$", views.linkedIn, name="linkedIn"),
    # This line has changed! Notice that urlpatterns is a list, the comma is in
]  # anticipation of all the routes that will be coming soon

portfolioproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(
        r"^", include("apps.portfolio.urls", namespace="portfolio")
    )  # And now we use the include function to pull in our first_app.urls...
]

apps/portfolio/models.py
from django.db import models

# Create your models here.

apps/portfolio/views.py
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.http import HttpResponse
from django.views.generic import View

from portfolioproject.utils import render_to_pdf


def main(req):
    return redirect("portfolio:home")


def home(req):
    return render(req, "portfolio/home.html")


def python(req):
    return render(req, "portfolio/python.html")


def csharp(req):
    return render(req, "portfolio/csharp.html")


def about(req):
    return render(req, "portfolio/about.html")


def contact(req):
    return redirect("portfolio/about/Pdf")


def Pdf(request, *args, **kwargs):
    pdf = render_to_pdf("portfolio/resume.html")
    if pdf:
        response = HttpResponse(pdf, content_type="application/pdf")
        filename = "resume_%s.pdf" % ("Elvis_Makia")
        content = "inline; filename='%s'" % (filename)
        download = request.GET.get("download")
        if download:
            content = "attachment; filename='%s'" % (filename)
        response["Content-Disposition"] = content
        return response
    return HttpResponse("Not found")


def wishmaker(req):
    return redirect("https://github.com/poferri/wishmaker.git")


def wishmakersite(req):
    return redirect("http://18.217.90.11/")


def quotedash(req):
    return redirect("https://github.com/poferri/quote_dash.git")


def quotedashsite(req):
    return redirect("http://52.14.128.79/")


def clakkle(req):
    return redirect("https://github.com/poferri/clakkle.git")


def clakklesite(req):
    return redirect("http://3.14.136.63/")


def weddingplanner(req):
    return redirect("https://github.com/poferri/WeddingPlanner.git")


def weddingplannersite(req):
    return redirect("http://18.222.165.8/")


def healthwall(req):
    return redirect("https://github.com/poferri/secrets.git")


def healthwallsite(req):
    return redirect("http://18.220.54.169/")


def linkedIn(req):
    return redirect("https://www.linkedin.com/in/elvismakia/")

apps/portfolio/templates/portfolio/about.html
{% extends "portfolio/base.html" %}

{% block content %}

{% load staticfiles %}
<style>
    .container {
        padding: 160px 80px 160px 80px;

    }

    #pdficon {
        height: 45px;
        width: 45px;
        margin-left: 20px;

    }
</style>
<div id="hoverDiv">

    <h3> Hello there and welcome to my portfolio site.</h3><br>
    <h3> I am Elvis. I have spent a little over a year already, coding with Python and Csharp and love every second of
        it!
    </h3><br>
    <h3> Although I am coming from an accounting background where I have spent time in Education and Government, I
        have worked as an SQL Data Analyst for a data consulting company, have gone through a popular coding bootcamp
        and
        have also built and deployed some functional projects in
        Python
        using Django as well as in Csharp using ASP.NETcore and employed full CRUD methodology.
    </h3><br>
    <h3>I currently have a graduate business degree, and a coding bootcamp certificate where I spent over
        10,000 hours coding and building projects in Python/Django and Csharp/ASP.NETcore.
        I am a quick learner, and an enthusiastic problem solver with experience in resolving complex
        issues.
    </h3><br>
    <h3>Please feel free to explore my portfolio site as much as possible and contact me with any questions you may
        have.
    </h3><br>

    <h3> I have included a link to a copy of my resume in printable and downloadable pdf format bellow.
        I can
        also be reached by email at clakkle@yahoo.com</h3>
    <br>
    <h3> Hope you have an enjoyable visit on the site .</h3> <br><br>
    <h3>Elvis</h3><br>

</div>

<a href="{% url 'portfolio:linkedIn' %}">
    <img id="linkediicon" src='{% static "portfolio/images/LinkedIn.png" %}' alt="LinkedIn">
</a>
|
<a href="{% url 'portfolio:Pdf' %}">
    <img id="pdficon" src='{% static "portfolio/images/pdficon.png" %}' alt="resume">
</a>

{% endblock content %}
{% block cameleon %}



<script>
    $(document).ready(function () {
        //this first function inide the hover method
        //is for when the mouse enters the element
        $('div#hoverDiv').hover(function () {
            //set multiple CSS properties at once
            $(this).css({
                'background-color': 'tomato',


            });
        }, function () {
            //set multiple CSS properties at once
            $(this).css({
                'background-color': '',

            });
        });
    });

</script>

{% endblock cameleon %}

apps/portfolio/templates/portfolio/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}

        {% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <style>
        body {
            background-color: dodgerblue;
            font-family: monospace;
            color: whitesmoke;
            height: auto;
            width: auto;

        }

        .container {

            background-color: salmon;
            width: auto;
            height: auto;
            margin: 0 auto;
            padding: 0 auto;
            padding-top: 20px;
            padding-bottom: 40px;
            border: 0px solid whitesmoke;
            border-radius: 0px;
            margin-bottom: 0px;
            margin-top: 0px;


        }


        div.jumbotron {
            background-color: black;
            width: auto;
            height: auto;
            margin: auto;
            padding: 30px 0px 30px 0px;
            border-radius: 0px;
            font-family: monospace;
            font-size: 33px;

        }



        #header,
        Ul,
        li,
        h1 {
            display: inline-block;
            vertical-align: top;
            padding: 0px 0px 0px 10px;
            color: white;
            margin-left: 30px;
            font-size: 28px;

        }

        Ul#header {
            margin: 20px 0px 0px 0px;
            height: 42px;
            width: 960px;
        }

        h2 {
            margin: 0px 0px 0px 0px;
            padding: 0px 0px 0px 0px;
            height: 72px;
            font-size: 60px;
            font-family: monospace;
        }



        footer.fixed-bottom,
        dl,
        dd {
            color: rgb(14, 81, 126);
            display: inline-block;
            vertical-align: top;
            text-align: center;
            padding: 2px 5px 2px 50px;
            font-size: 18px;

        }


        footer.fixed-bottom {
            background-color: azure;
            width: auto;
            height: 40px;
        }

        #image001,
        #image002,
        #image003 {
            height: 68px;
            width: 68px;
        }

        #LinkedIn {
            height: 100px;
            width: 100px;
        }



        @-webkit-keyframes bounce {

            from,
            20%,
            53%,
            80%,
            to {
                -webkit-animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
                animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
                -webkit-transform: translate3d(0, 0, 0);
                transform: translate3d(0, 0, 0);
            }

            40%,
            43% {
                -webkit-animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                -webkit-transform: translate3d(0, -30px, 0);
                transform: translate3d(0, -30px, 0);
            }

            70% {
                -webkit-animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                -webkit-transform: translate3d(0, -15px, 0);
                transform: translate3d(0, -15px, 0);
            }

            90% {
                -webkit-transform: translate3d(0, -4px, 0);
                transform: translate3d(0, -4px, 0);
            }
        }

        @keyframes bounce {

            from,
            20%,
            53%,
            80%,
            to {
                -webkit-animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
                animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
                -webkit-transform: translate3d(0, 0, 0);
                transform: translate3d(0, 0, 0);
            }

            40%,
            43% {
                -webkit-animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                -webkit-transform: translate3d(0, -30px, 0);
                transform: translate3d(0, -30px, 0);
            }

            70% {
                -webkit-animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                -webkit-transform: translate3d(0, -15px, 0);
                transform: translate3d(0, -15px, 0);
            }

            90% {
                -webkit-transform: translate3d(0, -4px, 0);
                transform: translate3d(0, -4px, 0);
            }
        }

        .bounce {
            -webkit-animation-name: bounce;
            animation-name: bounce;
            -webkit-transform-origin: center bottom;
            transform-origin: center bottom;
        }

        #image001 {
            /* This section calls the slideInFromrightt animation we defined above */
            animation: .8s ease-out .1s 20 bounce;
        }

        #image002 {
            /* This section calls the slideInFromrightt animation we defined above */
            animation: .8s ease-out .3s 20 bounce;
        }

        #image003 {
            /* This section calls the slideInFromrightt animation we defined above */
            animation: .8s ease-out .2s 20 bounce;
        }


        @-webkit-keyframes fadeInDown {
            from {
                opacity: 0;
                -webkit-transform: translate3d(0, -100%, 0);
                transform: translate3d(0, -100%, 0);
            }

            to {
                opacity: 1;
                -webkit-transform: translate3d(0, 0, 0);
                transform: translate3d(0, 0, 0);
            }
        }

        @keyframes fadeInDown {
            from {
                opacity: 0;
                -webkit-transform: translate3d(0, -100%, 0);
                transform: translate3d(0, -100%, 0);
            }

            to {
                opacity: 1;
                -webkit-transform: translate3d(0, 0, 0);
                transform: translate3d(0, 0, 0);
            }
        }

        .fadeInDown {
            -webkit-animation-name: fadeInDown;
            animation-name: fadeInDown;
        }




        li {
            /* This section calls the slideInFromrightt animation we defined above */
            animation: 3s ease-out .9s 1 fadeInDown;
        }
    </style>


</head>

<body>

    <div class="jumbotron">
        <h2>Elvis's <span class="spans">Portfolio</span></h2>

        <Ul id="header">
            <a href="{% url 'portfolio:home' %}">
                <li> <span class="spans">
                        Home
                    </span></li>
            </a>
            <a href="{% url 'portfolio:about' %}">
                <li> <span class="spans">
                        Aboutme
                    </span></li>
            </a>

            <a href="{% url 'portfolio:python' %}">
                <li> Python/Django </li>
            </a>
            <a href="{% url 'portfolio:csharp' %}">
                <li>C#/ASP.NETcore </li>
            </a>
        </Ul>
        <a href="{% url 'portfolio:home' %}">
            <img id="image001" src='{% static "portfolio/images/python.png" %}' alt="python">
            <img id="image002" src='{% static "portfolio/images/csharplogo.png" %}' alt="csharplogo">
            <img id="image003" src='{% static "portfolio/images/clakkle.png" %}' alt="clakkle">
        </a>
    </div>



    <div class="container">
        {% block content %}{% endblock content %}


    </div>


    <footer class="fixed-bottom">

        <dl id="footer">
            <a href="{% url 'portfolio:home' %}">
                <dd>Home </dd>
            </a>
            <a href="{% url 'portfolio:about' %}">
                <dd>About </dd>
            </a>
            <a href="{% url 'portfolio:python' %}">
                <dd>Python/Django</dd>
            </a>
            <a href="{% url 'portfolio:csharp' %}">
                <dd>C#/ASP.NETcore</dd><a>
                    <a href="{% url 'portfolio:Pdf' %}">
                        <dd> Contact</dd>
                    </a>

        </dl>


    </footer>




    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>


    </script>

    {% block cameleon %}


    {% endblock cameleon %}
</body>

</html>

apps/portfolio/templates/portfolio/csharp.html
{% extends "portfolio/base.html" %}

{% block title %}
ASP.NETcore
{% endblock title %}

{% block content %}

{% load staticfiles %}
<style>
    .container {
        padding: 70px 20px 70px 20px;


    }

    #icon01,
    #icon02 {
        display: inline-block;
        height: 138px;
        width: 138px;
    }

    #giticon {
        display: inline-block;

    }

    .subcontent1a {

        border-radius: 25px;
        margin: 80px 40px 40px 40px;
        font-size: 22px;

    }

    .subcontent1 .subcontent1a {

        width: 900px;
        height: 300px;
        padding: 450px 40x 40px 40px;
        text-align: left;




    }

    @keyframes rotatez {
        100% {
            transform: rotateZ(360deg);
        }
    }

    #icon01 {
        /* This section calls the slideInFromrightt animation we defined above */
        animation: .5s ease-out 1s 6 rotatez;
    }

    #icon02 {
        /* This section calls the slideInFromrightt animation we defined above */
        animation: .5s ease-out 2s 6 rotatez;
    }
</style>

<div class="container">
    <h1> <strong>Welcome to my C#/ASP.NETcore Projects page.</strong> </h1>
    <hr>
    <h1>Here, you will find two projects I bult with C#/ASP.NETcore.When you are done reading about a specific project,
        hit
        the C# icon to access the project. Once you hop on a project site , you have left this portfolio site. You would
        be able to find your way
        back. Hope you
        like my projects.
    </h1>
    <hr>



    <div id="subcontent1">

        <div id="hoverDiv" class="subcontent1a">
            <a href="{% url 'portfolio:weddingplannersite' %}">
                <img id="icon01" src='{% static "portfolio/images/csharplogo.png" %}' alt="csharplogo"></a>
            <a href="{% url 'portfolio:weddingplanner' %}">
                <img id="giticon" src='{% static "portfolio/images/githubimg.png" %}' alt="githubimage"></a>

            <h1> <strong> WEDDING PLANNER!!</strong></h1>
            <h3>In this first project, you will plan a wedding and have an option for guests to RSVP or Un-RSVP!</h3>
            <h3>A user should be able to create, edit, update and delete an item.</h3>
            <h3> It was bulit with ASP.NETcore framework and deployed using Amazon EC2 Web Services.</h3>
            <h3> A user should be able to signup and login with their newly created credentials. There is also an
                existing
                credential if you are pressed for time:
                Username: clakkle@yahoo.com PW: Clakkle#2019
            </h3>
            <hr>



        </div>
        <div id="hoverDiv" class="subcontent1a">
            <a href="{% url 'portfolio:healthwallsite' %}">
                <img id="icon02" src='{% static "portfolio/images/csharplogo.png" %}' alt="csharplogo">
            </a>
            <a href="{% url 'portfolio:healthwall' %}">
                <img id="giticon" src='{% static "portfolio/images/githubimg.png" %}' alt="githubimage">
            </a>
            <h1> <strong> HEALTH WALL!!</strong></h1>
            <h3>In this second project, you will suggest a healthy habit anyone can adopt. You will be posting on a
                wall!</h3>
            <h3> A user should be able to create, edit, update and delete an item.</h3>
            <h3> It was bulit with ASP.NETcore framework and deployed using Amazon EC2 Web Services.</h3>
            <h3> A user should be able to signup and login with their newly created credentials. Please use the
                following
                existing credentials if you are pressed for time:
                Username: clakkle@yahoo.com PW: Clakkle#2019
            </h3>


        </div>
    </div>
    {% endblock content %}


    {% block cameleon %}



    <script>
        $(document).ready(function () {
            //this first function inide the hover method
            //is for when the mouse enters the element
            $('div#hoverDiv').hover(function () {
                //set multiple CSS properties at once
                $(this).css({
                    'background-color': 'tomato',


                });
            }, function () {
                //set multiple CSS properties at once
                $(this).css({
                    'background-color': 'darkgrey',

                });
            });
        });

    </script>

    {% endblock cameleon %}

apps/portfolio/templates/portfolio/python.html
{% extends "portfolio/base.html" %}

{% block title %}
Python
{% endblock title %}

{% block content %}

{% load staticfiles %}

<style>
    .container {
        padding: 70px 20px 70px 20px;


    }

    #icon01,
    #icon02,
    #icon03,
    #icon04 {
        display: inline-block;
        height: 138px;
        width: 138px;
    }

    #giticon {
        display: inline-block;

    }


    .subcontent1a {

        border-radius: 25px;
        margin: 80px 40px 40px 40px;
        font-size: 22px;


    }

    .subcontent1 .subcontent1a {

        width: 950px;
        height: 500px;
        padding: 450px 40x 40px 40px;
        text-align: left;




    }





    @keyframes rotatez {
        100% {
            transform: rotateZ(360deg);
        }
    }

    #icon01 {
        /* This section calls the slideInFromrightt animation we defined above */
        animation: .5s ease-out 1s 3 rotatez;
    }

    #icon02 {
        /* This section calls the slideInFromrightt animation we defined above */
        animation: .5s ease-out 2s 4 rotatez;
    }

    #icon03 {
        /* This section calls the slideInFromrightt animation we defined above */
        animation: .5s ease-out 3s 5 rotatez;
    }

    #icon04 {
        /* This section calls the slideInFromrightt animation we defined above */
        animation: .5s ease-out 4s 5 rotatez;
    }
</style>
<div class="container">

    <div id="subcontent1">
        <h1><strong>Welcome to my Python/Django Projects page.</strong></h1>
        <hr>
        <h1>Here, you will find some projects I built using Python and Django. When you are done reading about a
            specific
            project, hit the python icon to access the project. Once you hop on a project site , you have left the
            portfolio site. You should be able to find
            your way back easily. Hope you
            like my projects.</h1>
        <hr>

        <div id="hoverDiv" class="subcontent1a">
            <a href="{% url 'portfolio:wishmakersite' %}">
                <img id="icon01" src='{% static "portfolio/images/python.png" %}' alt="pythonlogo"></a>
            <a href="{% url 'portfolio:wishmaker' %}">
                <img id="giticon" src='{% static "portfolio/images/githubimg.png" %}' alt="githubimage"></a>

            <h1> <strong> MAKE A WISH!!</strong></h1>
            <h3>In this first project, you will make a wish, and then grant your wish! You can wish for anything. Wish
                them !! Grant them!! And they will come! </h3>
            <h3>A user should be able to create, edit, update and delete an item.</h3>
            <h3> It was bulit with django framework and deployed using Amazon EC2 Web Services.</h3>
            <h3> A user should be able to signup and login with their newly created credentials. Please use the
                following
                existing credentials if you are pressed for time:
                Username: clakkle@yahoo.com PW: Clakkle#2019
            </h3>
            <hr>

        </div>
        <div id="hoverDiv" class="subcontent1a">
            <a href="{% url 'portfolio:quotedashsite' %}">
                <img id="icon02" src='{% static "portfolio/images/python.png" %}' alt="pythonlogo"></a>
            <a href="{% url 'portfolio:quotedash' %}">
                <img id="giticon" src='{% static "portfolio/images/githubimg.png" %}' alt="githubimage"></a>
            <h1><strong>WRITE A QUOTE</strong></h1>
            <h3>In this second project, you will be writing a quote from your favourite author on a wall !</h3>
            <h3>A user should be able to create, edit, update and delete an item as well.</h3>
            <h3> It was built with django framework and deployed using Amazon EC2 Web Services.</h3>
            <h3> One should be able to signup and login with their newly created credentials. Please use the following
                existing credentials if you are pressed for time:
                Username: clakkle@yahoo.com PW: Clakkle#2019
            </h3>
            <hr>
        </div>

        <div id="hoverDiv" class="subcontent1a">
            <a href="">
                <img id="icon03" src='{% static "portfolio/images/python.png" %}' alt="pythonlogo"></a>
            <a href="{% url 'portfolio:home' %}">
                <img id="giticon" src='{% static "portfolio/images/githubimg.png" %}' alt="githubimage"></a>

            <h1> <strong> MY PORTFOLIO SITE </strong></h1>
            <h3>My third project is my portfolio site. You are currently on it. It links all the various projects in my
                portfolio and was
                bulit with django framework and deployed using Amazon EC2 Web Services as well. You will be hoping in
                and out of it as you view the various projects. You will also be able to download or print out my resume
                in pdf format. </h3>
            <hr>


        </div>
        <div id="hoverDiv" class="subcontent1a">
            <a href="">
                <img id="icon04" src='{% static "portfolio/images/clakkle.png" %}' alt="clakklelogo"></a>
            <a href="{% url 'portfolio:clakkle' %}">
                <img id="giticon" src='{% static "portfolio/images/githubimg.png" %}' alt="githubimage"></a>

            <h1><strong> CLAKKLE </strong> </h1>
            <h3> In this last project, you will be able to record and play a voice recording. This one is a work in
                progress. But it is ambitious and interesting!</h3>
            <h3>A user should be able to create and delete an audio item. </h3>
            <h3> It was bulit with django framework. A getUserMedia() method was used in a pre scripted javascript
                function. The application was deployed using Amazon EC2 Web Services.</h3>
            <h3> One should be able to signup and login with newly created credentials. Please use the following
                existing credentials if you are pressed for time::
                Username: clakkle@yahoo.com PW: Clakkle#2019
            </h3>
        </div>

    </div>
</div>
{% endblock content %}


{% block cameleon %}



<script>
    $(document).ready(function () {
        //this first function inide the hover method
        //is for when the mouse enters the element
        $('div#hoverDiv').hover(function () {
            //set multiple CSS properties at once
            $(this).css({
                'background-color': 'tomato',


            });
        }, function () {
            //set multiple CSS properties at once
            $(this).css({
                'background-color': 'darkgrey',

            });
        });
    });

</script>

{% endblock cameleon %}